spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: web-service-user-server
          predicates:
            - Path=/hdsx/us/**
          filters:
            - StripPrefix=2
            - SwaggerHeaderFilter
          uri: lb://web-service-user-server
        - id: web-service-product-server
          predicates:
            - Path=/hdsx/ps/**
          filters:
            - StripPrefix=2
            - SwaggerHeaderFilter
          uri: lb://web-service-product-server
        - id: web-service-order-server
          predicates:
            - Path=/hdsx/os/**
          filters:
            - StripPrefix=2
            - SwaggerHeaderFilter
          uri: lb://web-service-order-server
        - id: web-service-media-server
          predicates:
            - Path=/hdsx/ms/**
          filters:
            - StripPrefix=2
            - SwaggerHeaderFilter
          uri: lb://web-service-media-server
        - id: web-service-redis-server
          predicates:
            - Path=/hdsx/rs/**
          filters:
            - StripPrefix=2
            - SwaggerHeaderFilter
          uri: lb://web-service-redis-server
  application:
    name: web-service-gateway #给你的微服务应用起一名字
server:
  port: 40012
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:40000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
